# Generated by Django 3.2 on 2021-04-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='pics')),
                ('authorid', models.CharField(max_length=12)),
                ('collegename', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CSE', 'cse'), ('ECE', 'ece'), ('EEE', 'eee'), ('MECH', 'mech'), ('CIVIL', 'civil'), ('MCA', 'mca')], max_length=10)),
                ('dob', models.DateField()),
                ('academic_year', models.CharField(choices=[('FIRST Year', 'first year'), ('SECOND YEAR', 'second year'), ('THIRD YEAR', 'third year'), ('FINAL YEAR', 'final year')], max_length=20)),
                ('phno', models.CharField(max_length=13)),
            ],
        ),
    ]
